Updated azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -3,6 +3,7 @@ trigger:
     include:
       - main
       - feature/*
+
 variables: 
   - group: 'USERS_API_VARIABLE_GROUP'
   - name: DockerId
@@ -13,15 +14,19 @@ variables:
     value: "$(DOCKER_REPO)"
   - name: ServiceName
     value: "$(SERVICE_NAME)"
+
 pool:
   vmImage: 'ubuntu-latest'
+
 resources:
   repositories:
     - repository: users-api
       type: git
       ref: 'refs/heads/main'
       name: user-api
+
 stages:
+
   # === STAGE 1: PRE-BUILD ===
   - stage: PreBuild
     displayName: 'Pre-Build'
@@ -38,18 +43,19 @@ stages:
             persistCredentials: true
 
           - script: |
-              chmod +x "$(Build.SourcesDirectory)/users-api/logging.sh" 
-              chmod +x "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh" 
+              chmod +x "$(Build.SourcesDirectory)/users-api/logging.sh"
+              chmod +x "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
             displayName: 'Make scripts executable'
 
-          - script:|
-              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/logging.sh"  
-              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh" 
-            displayName: 'Fix line endings in scripts'  
+          - script: |
+              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/logging.sh"
+              sed -i 's/\r$//' "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
+            displayName: 'Fix line endings in scripts'
 
-          -script: |
+          - script: |
               . "$(Build.SourcesDirectory)/users-api/logging.sh"
-              info_msg "Run logging script"  
+              info_msg "Run logging script"
+            displayName: 'Run Logging Script'
 
           - task: Bash@3
             displayName: 'Print Azure DevOps Pipeline predefined variables'
@@ -57,39 +63,40 @@ stages:
               targetType: 'inline'
               script: |
                 . "$(Build.SourcesDirectory)/users-api/logging.sh"
-                info_msg "Docker ID - $(DockerID)"
-                info_msg "Docker Repo - $(DpckerRepo)"
+                info_msg "Docker ID - $(DockerId)"
+                info_msg "Docker Repo - $(DockerRepo)"
                 info_msg "Service Name - $(ServiceName)"
-                if [ -z "(MANUALLY_SETUP_APP_VERSION)"] ; then
+                if [ -z "$MANUALLY_SETUP_APP_VERSION" ]; then
                   info_msg "MANUALLY_SETUP_APP_VERSION is not set"
                 else
-                  info_msg "MANUALLY_SETUP_APP_VERSION is  set to (MANUALLY_SETUP_APP_VERSION)"    
+                  info_msg "MANUALLY_SETUP_APP_VERSION is set to $MANUALLY_SETUP_APP_VERSION"
                 fi
+
           - task: Bash@3
             name: setAppVersionStep
-            displayName:  'Set APP_VERSION output variable'
+            displayName: 'Set APP_VERSION output variable'
             inputs:
               targetType: 'inline'
-              script:
-                 source "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
+              script: |
+                source "$(Build.SourcesDirectory)/users-api/common-script/dockerhub.sh"
 
-                 latest_git_tag=$(get_docker_image_latest_version $(DockerRepo) $(DockerId) $(DockerToken))
-                 exit_code=$?
+                latest_git_tag=$(get_docker_image_latest_version $(DockerRepo) $(DockerId) $(DockerToken))
+                exit_code=$?
 
-                 if [[$exit_code -eq 1]]; then
-                    info_msg "Login failed. Please check your username and password."
-                    exit 1
-                 elif [[ $exit_code -eq 2]]; then
-                     info_msg "Invalid version format."    
-                    exit 2
-                  fi
+                if [[ $exit_code -eq 1 ]]; then
+                  echo "Login failed. Please check your username and password."
+                  exit 1
+                elif [[ $exit_code -eq 2 ]]; then
+                  echo "Invalid version format."
+                  exit 2
+                fi
 
-                  echo "latest_git_tag=$latest_git_tag"
-                  if [-z "latest_git_tag"]; then
-                  echo "APP_VERSION not retrieved. Exiting..."  
+                echo "latest_git_tag=$latest_git_tag"
+                if [ -z "$latest_git_tag" ]; then
+                  echo "APP_VERSION not retrieved. Exiting..."
                   exit 3
-                  fi
-                  
+                fi
+
   # === STAGE 2: BUILD AND TEST ===
   - stage: BuildAndTest
     displayName: 'Project: Build and Test'
@@ -130,8 +137,8 @@ stages:
           - task: Docker@2
             displayName: 'Build Docker Image'
             inputs:
-              containerRegistry: 'sillerolena'  # ← укажи свой сервис-коннекшн
-              repository: 'sillerolena/lab4' # ← укажи свой dockerhub repo
+              containerRegistry: 'sillerolena'
+              repository: 'sillerolena/lab4'
               command: 'build'
               Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
               buildContext: '$(Build.SourcesDirectory)'
@@ -144,7 +151,7 @@ stages:
             displayName: 'Push Docker Image'
             inputs:
               containerRegistry: 'sillerolena'
-              repository: sillerolena'
+              repository: 'sillerolena/lab4'
               command: 'push'
               tags: |
                 $(Build.BuildId)
@@ -176,6 +183,7 @@ stages:
           - script: |
               echo "Post-build cleanup or report step"
             displayName: 'Post-Build Step'
+
 
 
 
