Updated azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,7 +9,6 @@ pool:
 
 stages:
 
-
 - stage: PreBuild
   displayName: 'Pre-Build Stage'
   jobs:
@@ -33,22 +32,37 @@ stages:
   - job: BuildTest
     displayName: 'Build and Test'
     steps:
+
+    # Проверка, установлен ли Python, если нет - установка
+    - script: |
+        echo "Checking if Python is installed..."
+        python --version || (echo "Python not found. Installing Python..."; sudo apt-get update; sudo apt-get install -y python3 python3-pip)
+      displayName: 'Check and Install Python'
+
+    # Проверка, установлен ли pip, если нет - установка
+    - script: |
+        echo "Checking if pip is installed..."
+        pip --version || (echo "pip not found. Installing pip..."; sudo apt-get install -y python3-pip)
+      displayName: 'Check and Install pip'
+
+    # Установка зависимостей
     - script: |
         echo "Installing Python dependencies..."
         python -m pip install --upgrade pip
         pip install -r requirements.txt
       displayName: 'Install Requirements'
 
+    # Установка pytest
     - script: |
         echo "Installing pytest..."
-        pip install pytest  
+        pip install pytest
       displayName: 'Install pytest'
 
+    # Запуск тестов
     - script: |
         echo "Running tests with pytest..."
-        pytest   # Запускаем тесты
+        pytest
       displayName: 'Run Tests'
-
 
 
 - stage: DockerBuildAndPush
@@ -60,17 +74,19 @@ stages:
     displayName: 'Docker Build and Push'
     steps:
 
+    # Логин в Docker
     - script: |
         echo "Logging in to Docker Hub..."
         echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
       displayName: '**Docker Login**'
 
+    # Построение и пуш Docker образа
     - script: |
         IMAGE_NAME=$(DOCKER_USERNAME)/sillerolena:$(Build.BuildId)
         echo "Building Docker image: $IMAGE_NAME"
-        docker build -t $IMAGE_NAME.
+        docker build -t $IMAGE_NAME .
 
-        echo "Pushing Docker $IMAGE_NAME"
+        echo "Pushing Docker image: $IMAGE_NAME"
         docker push $IMAGE_NAME
       displayName: '**Docker Build & Push**'
 
@@ -88,7 +104,6 @@ stages:
         helm package ./chart
 
         echo "Pushing Helm chart to repository..."
-        # Make sure 'helm push' plugin is installed
         # helm push ./chart-*.tgz my-helm-repo
       displayName: 'Pack & Push Helm Chart'
 
